### PR TITLE
Add by Nur (New design of landingpage)

### PR DESCRIPTION
**Pull request by nurofsun**
I already make new design for landingpage of degenbanana, it optimized and using tailwindcss. Please leave your feedback.

### CODE REVIEW

**Comment by degenbananasol** [comment]
Very nice thanks for the contribution @nurofsun!

Some suggestions (just our opinion / taste):

1. can logo be all lower case 'degenbanana'

image

2. maybe small space in here

image

3. This phrase is very corporate. Can we replace it with 'Let's get slippery.'

image

4. The dark background a little too dark / doesn't fit the warm / bright pastel color theme. Can it instead be pastel pink or blue?

Thanks!

**Comment by nurofsun** [comment]
I don't understand with suggestion number 2, can you explain more detail. Sorry my bad english sir!

**Comment by nurofsun** [comment]
I will working on other suggestions now!

**Comment by degenbananasol** [comment]
> I don't understand with suggestion number 2, can you explain more detail. Sorry my bad english sir!

Number 2 just put some small line spacing / padding between the large font and small font. Looks a bit too tight.

**Comment by nurofsun** [comment]
image
is it enough? and how about the navbar? should I change the background color too?

**Comment by degenbananasol** [comment]
Maybe yes. Warm / pastel colors. Light orange maybe? You choose you're the designer.

**Comment by nurofsun** [comment]
I will update it later, stay tuned for new changes sir :)

**Comment by degenbananasol** [comment]
OK thanks for the submission looks like the current landing page won the community vote!

**Pull request closed without merging**
